// Copyright (c) 2026 Hemashushu <hippospark@gmail.com>, All rights reserved.
//
// This Source Code Form is subject to the terms of
// the Mozilla Public License version 2.0 and additional exceptions.
// For more details, see the LICENSE, LICENSE.additional, and CONTRIBUTING files.

// ANCPP reserves file number 0 for predefined macros.
pub const FILE_NUMBER_PREDEFINED: usize = 0;

// ANCPP automatically assigns file numbers to **header files**, starting from 1
// (file number 0 is reserved for predefined macros).
//
// However, the number of **source files** are specified manually using
// the `source_file_number` parameter of function `process_source_file`.
//
// To avoid conflicts with header files, this file number should be greater than
// or equal to `FILE_NUMBER_SOURCE_FILE_BEGIN`, which is defined as 65536.
pub const FILE_NUMBER_SOURCE_FILE_BEGIN: usize = 2_usize.pow(16);

// Message that generated by the directive `warn`.
// Lint level: Warn
pub const LINT_SUPPRESS_DIRECTIVE_WARN: &str = "directive_warn";

// A header file does not have `#pragma once` or include guard.
// Lint level: Warn
pub const LINT_SUPPRESS_INCLUDE_GUARD_ABSENT: &str = "include_guard_absent";

// A header file has an include guard, but it is recommended to use `#pragma once` for better practice.
// Lint level: Info
pub const LINT_SUPPRESS_TRADITIONAL_INCLUDE_GUARD: &str = "traditional_include_guard";

// The include guard macro name does not follow the convention of being in uppercase and ending with `FILE_NAME_H`.
// Lint level: Info
pub const LINT_SUPPRESS_UNCONVENTIONAL_INCLUDE_GUARD: &str = "unconventional_include_guard";

// A macro invocation argument contains multiple tokens, which may lead to unexpected behaviors.
// Lint level: Info
pub const LINT_SUPPRESS_MACRO_INVOCATION_SINGLE_ARGUMENT_MULTIPLE_TOKENS: &str =
    "macro_invocation_single_argument_multiple_tokens";

// A macro is redefined with an identical replacement, which is redundant and may indicate a mistake.
// Lint level: Info
pub const LINT_SUPPRESS_IDENTICAL_REDEFINITION: &str = "identical_redefinition";

// A macro that has not been defined is undefined using `#undef`, which may indicate a mistake.
// Lint level: Warn
pub const LINT_SUPPRESS_UNDEF_NONEXISTENT_MACRO: &str = "undef_nonexistent_macro";

// This flag controls whether to resolve file paths that are relative to the current file.
//
// By default, ANCPP only resolves header and resource files located in the user and
// system directories specified in the `FileProvider`, this strategy improves
// consistency and security.
//
// For example, consider there are 3 defined include directories:
//
// - `./include`
// - `./src/headers`
// - `/usr/include`
//
// The statement `#include "foo.h"` in the source file `src/main.c` will try to
// match `foo.h` in the following order:
//
// - `./include/foo.h`
// - `./src/headers/foo.h`
// - `/usr/include/foo.h`
//
// If this flag is set to `true`, then it will also try to match `src/foo.h`,
// which is relative to the current file `src/main.c`.
//
// Most C compilers, such as GCC and Clang (LLVM), resolve relative paths which is
// related to the current file being compiled. If you want to match this behavior,
// set this flag to `true`.
pub const COMPILE_FEATURE_RESOLVE_HEADER_FILE_RELATIVE_TO_CURRENT_FILE: &str =
    "resolve_header_file_relative_to_current_file";

// By default, ANCPP requires each macro invocation argument to be a single token
// (identifier, number, string literal, character literal, or punctuator).
// If this flag is set to `true`, an argument may be an arbitrary sequence of tokens,
// allowing more complex expressions to be passed as a single parameter,
// but it may lead to unexpected behaviors, especially when the arguments
// have side effects or involve complex expressions.
// It is recommended to keep this flag disabled.
pub const COMPILE_FEATURE_MACRO_INVOCATION_SINGLE_ARGUMENT_MULTIPLE_TOKENS: &str =
    "macro_invocation_single_argument_multiple_tokens";

// C23 keywords
// It is used to prevent keywords from being used as macro names in the preprocessor.
//
// This list contains all C keywords, including those introduced in C23,
// but excludes any keywords that have been deprecated or removed in C23.
//
// - `_Alignas` (C11)(deprecated in C23) -> `alignas` (C23)
// - `_Alignof` (C11)(deprecated in C23) -> `alignof` (C23)
// - `_Bool` (C99)(deprecated in C23) -> `bool` (C23)
// - `_Static_assert` (C11)(deprecated in C23) -> `static_assert` (C23)
// - `_Thread_local` (C11)(deprecated in C23) -> `thread_local` (C23)
// - `_Noreturn` (C11)(deprecated in C23)
//
// Reference:
// - https://cppreference.com/c/keyword
// - https://en.cppreference.com/w/c/keyword.html
pub const C23_KEYWORD_STRS: [&str; 53] = [
    /* storage class specifier */
    "typedef",
    "extern",
    "static",
    "thread_local",
    "auto",
    "register",
    "constexpr",
    /* type specifier */
    "void",
    "char",
    "short",
    "int",
    "long",
    "float",
    "double",
    "signed",
    "unsigned",
    "bool",
    "_Complex",
    "_Imaginary",
    "_Decimal32",
    "_Decimal64",
    "_Decimal128",
    "_BitInt",
    "typeof",
    "typeof_unqual",
    "_Atomic",
    "struct",
    "union",
    "enum",
    /* type qualifier */
    "const",
    "restrict",
    "volatile",
    /* function specifier */
    "inline",
    /* alignment specifier */
    "alignas",
    /* other keywords */
    "if",
    "else",
    "switch",
    "case",
    "default",
    "break",
    "continue",
    "for",
    "do",
    "while",
    "false",
    "true",
    "goto",
    "return",
    "alignof",
    "sizeof",
    "nullptr",
    "static_assert",
    "_Generic",
];

#[repr(usize)]
pub enum C23Keyword {
    /* storage class specifier */
    Typedef,
    Extern,
    Static,
    ThreadLocal,
    Auto,
    Register,
    Constexpr,
    /* type specifier */
    Void,
    Char,
    Short,
    Int,
    Long,
    Float,
    Double,
    Signed,
    Unsigned,
    Bool,
    Complex,
    Imaginary,
    Decimal32,
    Decimal64,
    Decimal128,
    BitInt,
    Typeof,
    TypeofUnqual,
    Atomic,
    Struct,
    Union,
    Enum,
    /* type qualifier */
    Const,
    Restrict,
    Volatile,
    /* function specifier */
    Inline,
    /* alignment specifier */
    Alignas,
    /* other keywords */
    If,
    Else,
    Switch,
    Case,
    Default,
    Break,
    Continue,
    For,
    Do,
    While,
    False,
    True,
    Goto,
    Return,
    Alignof,
    Sizeof,
    Nullptr,
    StaticAssert,
    Generic,
}
